version: '3.3'
services:
  node:
    build: .
    ports:
      - 3000:3000
    volumes:
      - ./react-project/src/:/app/src/
      - ./react-project/public/:/app/public/
      - ./react-project/build/:/app/build/
      - ./react-project/package.json:/app/package.json